apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: alertmanager
    spec:
      containers:
        - args:
            - --config.file=/etc/alertmanager/alertmanager.yaml
            - --storage.path=/alertmanager
          image: prom/alertmanager
          name: alertmanager
          ports:
            - containerPort: 9093
          resources: {}
          volumeMounts:
            - mountPath: /etc/alertmanager/alertmanager.yaml
              name: alertmanager-claim0
      restartPolicy: Always
      volumes:
        - name: alertmanager-claim0
          persistentVolumeClaim:
            claimName: alertmanager-claim0
status: {}
